name: Coding Standards

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-20.04
    env:
      SWOOLE_DOCKER_VERSION: 4.7-php7.4
      POSTGRESQL_VERSION: f5eda17f89d160d0a89ac7c5db4636bdaefd48e6
      ENV_SERVICE: swoole-only
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          docker-compose -f ./.github/docker-compose.yml up -d ${ENV_SERVICE}
          docker exec ${ENV_SERVICE} php -v
          docker exec ${ENV_SERVICE} composer -V
          docker exec ${ENV_SERVICE} composer update --no-interaction --prefer-dist --no-progress
          docker exec ${ENV_SERVICE} bash -c "cd split-repository && composer install --no-interaction --prefer-dist --no-progress"

      - name: Coding Standards Tests
        run: docker exec ${ENV_SERVICE} ./vendor/bin/php-cs-fixer fix --dry-run --diff
